In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
car_data=pd.read_csv('/content/sample_data/CarPrice_Assignment.csv')

In [6]:
car_data

     car_ID  symboling                   CarName  ... citympg highwaympg    price
0         1          3        alfa-romero giulia  ...      21         27  13495.0
1         2          3       alfa-romero stelvio  ...      21         27  16500.0
2         3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3         4          2               audi 100 ls  ...      24         30  13950.0
4         5          2                audi 100ls  ...      18         22  17450.0
..      ...        ...                       ...  ...     ...        ...      ...
200     201         -1           volvo 145e (sw)  ...      23         28  16845.0
201     202         -1               volvo 144ea  ...      19         25  19045.0
202     203         -1               volvo 244dl  ...      18         23  21485.0
203     204         -1                 volvo 246  ...      26         27  22470.0
204     205         -1               volvo 264gl  ...      19         25  22625.0

[205 rows x 26 columns]

In [7]:
car_data.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [9]:
car_data.isnull().sum().sum()

0

In [10]:
car_data.drop(['car_ID'],axis=1,inplace=True)

In [11]:
car_data

     symboling                   CarName fueltype  ... citympg highwaympg    price
0            3        alfa-romero giulia      gas  ...      21         27  13495.0
1            3       alfa-romero stelvio      gas  ...      21         27  16500.0
2            1  alfa-romero Quadrifoglio      gas  ...      19         26  16500.0
3            2               audi 100 ls      gas  ...      24         30  13950.0
4            2                audi 100ls      gas  ...      18         22  17450.0
..         ...                       ...      ...  ...     ...        ...      ...
200         -1           volvo 145e (sw)      gas  ...      23         28  16845.0
201         -1               volvo 144ea      gas  ...      19         25  19045.0
202         -1               volvo 244dl      gas  ...      18         23  21485.0
203         -1                 volvo 246   diesel  ...      26         27  22470.0
204         -1               volvo 264gl      gas  ...      19         25  22625.0

[205 rows x 25 columns]

In [13]:
df1=car_data.drop(['symboling','wheelbase', 'carlength','carwidth', 'carheight', 'curbweight','enginesize', 'boreratio', 'stroke', 'compressionratio','horsepower', 'peakrpm', 'citympg', 'highwaympg', 'price'],axis=1)

In [14]:
df1

                      CarName fueltype  ... cylindernumber fuelsystem
0          alfa-romero giulia      gas  ...           four       mpfi
1         alfa-romero stelvio      gas  ...           four       mpfi
2    alfa-romero Quadrifoglio      gas  ...            six       mpfi
3                 audi 100 ls      gas  ...           four       mpfi
4                  audi 100ls      gas  ...           five       mpfi
..                        ...      ...  ...            ...        ...
200           volvo 145e (sw)      gas  ...           four       mpfi
201               volvo 144ea      gas  ...           four       mpfi
202               volvo 244dl      gas  ...            six       mpfi
203                 volvo 246   diesel  ...            six        idi
204               volvo 264gl      gas  ...           four       mpfi

[205 rows x 10 columns]

In [15]:
dummy_df=pd.get_dummies(df1,columns=['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody','drivewheel', 'enginelocation', 'enginetype', 'cylindernumber','fuelsystem'])

In [16]:
dummy_df

     CarName_Nissan versa  ...  fuelsystem_spfi
0                       0  ...                0
1                       0  ...                0
2                       0  ...                0
3                       0  ...                0
4                       0  ...                0
..                    ...  ...              ...
200                     0  ...                0
201                     0  ...                0
202                     0  ...                0
203                     0  ...                0
204                     0  ...                0

[205 rows x 185 columns]

In [18]:
df2=car_data.drop(['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody','drivewheel', 'enginelocation', 'enginetype', 'cylindernumber','fuelsystem'],axis=1)

In [19]:
df2

     symboling  wheelbase  carlength  ...  citympg  highwaympg    price
0            3       88.6      168.8  ...       21          27  13495.0
1            3       88.6      168.8  ...       21          27  16500.0
2            1       94.5      171.2  ...       19          26  16500.0
3            2       99.8      176.6  ...       24          30  13950.0
4            2       99.4      176.6  ...       18          22  17450.0
..         ...        ...        ...  ...      ...         ...      ...
200         -1      109.1      188.8  ...       23          28  16845.0
201         -1      109.1      188.8  ...       19          25  19045.0
202         -1      109.1      188.8  ...       18          23  21485.0
203         -1      109.1      188.8  ...       26          27  22470.0
204         -1      109.1      188.8  ...       19          25  22625.0

[205 rows x 15 columns]

In [22]:
final_df=pd.concat([df2,dummy_df],axis=1)

In [23]:
final_df

     symboling  wheelbase  ...  fuelsystem_spdi  fuelsystem_spfi
0            3       88.6  ...                0                0
1            3       88.6  ...                0                0
2            1       94.5  ...                0                0
3            2       99.8  ...                0                0
4            2       99.4  ...                0                0
..         ...        ...  ...              ...              ...
200         -1      109.1  ...                0                0
201         -1      109.1  ...                0                0
202         -1      109.1  ...                0                0
203         -1      109.1  ...                0                0
204         -1      109.1  ...                0                0

[205 rows x 200 columns]

In [24]:
x=final_df.drop(['price'],axis=1)

In [25]:
x

     symboling  wheelbase  ...  fuelsystem_spdi  fuelsystem_spfi
0            3       88.6  ...                0                0
1            3       88.6  ...                0                0
2            1       94.5  ...                0                0
3            2       99.8  ...                0                0
4            2       99.4  ...                0                0
..         ...        ...  ...              ...              ...
200         -1      109.1  ...                0                0
201         -1      109.1  ...                0                0
202         -1      109.1  ...                0                0
203         -1      109.1  ...                0                0
204         -1      109.1  ...                0                0

[205 rows x 199 columns]

In [26]:
y=fina_df[['price']]

In [27]:
y

       price
0    13495.0
1    16500.0
2    16500.0
3    13950.0
4    17450.0
..       ...
200  16845.0
201  19045.0
202  21485.0
203  22470.0
204  22625.0

[205 rows x 1 columns]

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [32]:
x_train.shape

(143, 199)

In [33]:
x_test.shape

(62, 199)

In [35]:
y_train.shape

(143, 1)

In [ ]:
y_test.shape

In [36]:
from sklearn.preprocessing import MinMaxScaler

In [37]:
mmc=MinMaxScaler()

In [40]:
x_train_mmc=mmc.fit_transform(x_train)
x_test_mmc=mmc.transform(x_test)

In [41]:
y_train_mmc=mmc.fit_transform(y_train)
y_test_mmc=mmc.transform(y_test)

In [42]:
x_train_mmc.shape

(143, 199)

In [43]:
x_test.shape

(62, 199)

In [44]:
y_train.shape

(143, 1)

In [45]:
y_test.shape

(62, 1)

In [47]:
import tensorflow as tf
from keras import models
from keras import layers
def build_model(act):
 model = models.Sequential()
 model.add(layers.Dense(128, activation=act,input_shape=(199,)))
 model.add(layers.Dense(64, activation=act))
 model.add(layers.Dense(32, activation=act))
 model.add(layers.Dense(1))
 model.compile(optimizer='adam', loss='mse', metrics=['mae'])
 return model

In [48]:
import numpy as np
k = 4
num_val_samples = len(x_train_mmc) // k
num_epochs = 100
all_scores = []
for i in range(k):
 print('processing fold #', i)
 val_data = x_train_mmc[i * num_val_samples: (i + 1) * num_val_samples]
 val_targets = y_train_mmc[i * num_val_samples: (i + 1) * num_val_samples]
 partial_train_data = np.concatenate([x_train_mmc[:i * num_val_samples],x_train_mmc[(i + 1) * num_val_samples:]],axis=0)
 partial_train_targets = np.concatenate([y_train_mmc[:i * num_val_samples],y_train_mmc[(i + 1) * num_val_samples:]],axis=0)
 model = build_model('tanh')
 model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
 val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
 all_scores.append(val_mae)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3

In [49]:
all_scores

[0.04936418682336807,
 0.05722338706254959,
 0.05486039072275162,
 0.05497586727142334]

In [50]:
np.mean(all_scores)

0.054105957970023155

In [51]:
model_tanh=build_model('tanh')
model_tanh.fit(x_train_mmc,y_train_mmc,epochs=100,batch_size=1)

Epoch 1/100
143/143 [==============================] - 1s 2ms/step - loss: 0.0776 - mae: 0.2210
Epoch 2/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0135 - mae: 0.0908
Epoch 3/100
143/143 [==============================] - 0s 1ms/step - loss: 0.0038 - mae: 0.0475
Epoch 4/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0050 - mae: 0.0554
Epoch 5/100
143/143 [==============================] - 0s 1ms/step - loss: 0.0061 - mae: 0.0625
Epoch 6/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0038 - mae: 0.0491
Epoch 7/100
143/143 [==============================] - 0s 1ms/step - loss: 0.0035 - mae: 0.0471
Epoch 8/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0032 - mae: 0.0400
Epoch 9/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0057 - mae: 0.0532
Epoch 10/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0036 - mae: 0.0425
Epoch 11/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0072 - mae: 0.0667
Epoch 12/100
143/143 [==============================] - 0s 1ms/step - loss: 0.0058 - mae: 0.0588
Epoch 13/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0025 - mae: 0.0354
Epoch 14/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0035 - mae: 0.0464
Epoch 15/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0024 - mae: 0.0384
Epoch 16/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0025 - mae: 0.0391
Epoch 17/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0019 - mae: 0.0345
Epoch 18/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0014 - mae: 0.0298
Epoch 19/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0018 - mae: 0.0312
Epoch 20/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0015 - mae: 0.0313
Epoch 21/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0012 - mae: 0.0258
Epoch 22/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0023 - mae: 0.0342
Epoch 23/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0054 - mae: 0.0549
Epoch 24/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0104 - mae: 0.0754
Epoch 25/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0031 - mae: 0.0405
Epoch 26/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0029 - mae: 0.0344
Epoch 27/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0017 - mae: 0.0316
Epoch 28/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0029 - mae: 0.0416
Epoch 29/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0010 - mae: 0.0248
Epoch 30/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0025 - mae: 0.0407
Epoch 31/100
143/143 [==============================] - 0s 2ms/step - loss: 7.1886e-04 - mae: 0.0207
Epoch 32/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0020 - mae: 0.0316
Epoch 33/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0018 - mae: 0.0298
Epoch 34/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0022 - mae: 0.0358
Epoch 35/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0013 - mae: 0.0281
Epoch 36/100
143/143 [==============================] - 0s 2ms/step - loss: 9.1804e-04 - mae: 0.0235
Epoch 37/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0014 - mae: 0.0297
Epoch 38/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0013 - mae: 0.0270
Epoch 39/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0011 - mae: 0.0232
Epoch 40/100
143/143 [==============================] - 0s 1ms/step - loss: 9.4115e-04 - mae: 0.0218
Epoch 41/100
143/143 [==============================] - 0s 1ms/step - loss: 0.0012 - mae: 0.0260
Epoch 42/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0012 - mae: 0.0274
Epoch 43/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0018 - mae: 0.0346
Epoch 44/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0015 - mae: 0.0289
Epoch 45/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0030 - mae: 0.0432
Epoch 46/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0015 - mae: 0.0272
Epoch 47/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0016 - mae: 0.0284
Epoch 48/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0012 - mae: 0.0245
Epoch 49/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0033 - mae: 0.0364
Epoch 50/100
143/143 [==============================] - 0s 1ms/step - loss: 0.0014 - mae: 0.0279
Epoch 51/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0017 - mae: 0.0313
Epoch 52/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0022 - mae: 0.0356
Epoch 53/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0011 - mae: 0.0256
Epoch 54/100
143/143 [==============================] - 0s 2ms/step - loss: 6.3954e-04 - mae: 0.0194
Epoch 55/100
143/143 [==============================] - 0s 1ms/step - loss: 6.2866e-04 - mae: 0.0204
Epoch 56/100
143/143 [==============================] - 0s 2ms/step - loss: 5.7762e-04 - mae: 0.0183
Epoch 57/100
143/143 [==============================] - 0s 2ms/step - loss: 6.2917e-04 - mae: 0.0201
Epoch 58/100
143/143 [==============================] - 0s 2ms/step - loss: 5.6891e-04 - mae: 0.0176
Epoch 59/100
143/143 [==============================] - 0s 2ms/step - loss: 7.0177e-04 - mae: 0.0205
Epoch 60/100
143/143 [==============================] - 0s 2ms/step - loss: 8.4497e-04 - mae: 0.0231
Epoch 61/100
143/143 [==============================] - 0s 2ms/step - loss: 5.8568e-04 - mae: 0.0168
Epoch 62/100
143/143 [==============================] - 0s 2ms/step - loss: 8.3287e-04 - mae: 0.0215
Epoch 63/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0012 - mae: 0.0270
Epoch 64/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0017 - mae: 0.0341
Epoch 65/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0017 - mae: 0.0299
Epoch 66/100
143/143 [==============================] - 0s 2ms/step - loss: 8.1884e-04 - mae: 0.0227
Epoch 67/100
143/143 [==============================] - 0s 2ms/step - loss: 5.5274e-04 - mae: 0.0183
Epoch 68/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0016 - mae: 0.0299
Epoch 69/100
143/143 [==============================] - 0s 1ms/step - loss: 0.0010 - mae: 0.0229
Epoch 70/100
143/143 [==============================] - 0s 2ms/step - loss: 8.0909e-04 - mae: 0.0211
Epoch 71/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0022 - mae: 0.0383
Epoch 72/100
143/143 [==============================] - 0s 1ms/step - loss: 7.6735e-04 - mae: 0.0203
Epoch 73/100
143/143 [==============================] - 0s 2ms/step - loss: 6.2108e-04 - mae: 0.0181
Epoch 74/100
143/143 [==============================] - 0s 2ms/step - loss: 4.5021e-04 - mae: 0.0159
Epoch 75/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0014 - mae: 0.0284
Epoch 76/100
143/143 [==============================] - 0s 2ms/step - loss: 7.4846e-04 - mae: 0.0215
Epoch 77/100
143/143 [==============================] - 0s 2ms/step - loss: 8.9008e-04 - mae: 0.0210
Epoch 78/100
143/143 [==============================] - 0s 2ms/step - loss: 4.8018e-04 - mae: 0.0165
Epoch 79/100
143/143 [==============================] - 0s 2ms/step - loss: 8.5524e-04 - mae: 0.0226
Epoch 80/100
143/143 [==============================] - 0s 2ms/step - loss: 5.5166e-04 - mae: 0.0173
Epoch 81/100
143/143 [==============================] - 0s 2ms/step - loss: 4.5827e-04 - mae: 0.0164
Epoch 82/100
143/143 [==============================] - 0s 2ms/step - loss: 9.8841e-04 - mae: 0.0244
Epoch 83/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0011 - mae: 0.0243
Epoch 84/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0018 - mae: 0.0271
Epoch 85/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0020 - mae: 0.0300
Epoch 86/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0034 - mae: 0.0452
Epoch 87/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0019 - mae: 0.0304
Epoch 88/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0012 - mae: 0.0230
Epoch 89/100
143/143 [==============================] - 0s 1ms/step - loss: 9.7735e-04 - mae: 0.0221
Epoch 90/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0026 - mae: 0.0237
Epoch 91/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0063 - mae: 0.0552
Epoch 92/100
143/143 [==============================] - 0s 2ms/step - loss: 9.3454e-04 - mae: 0.0220
Epoch 93/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0010 - mae: 0.0230
Epoch 94/100
143/143 [==============================] - 0s 2ms/step - loss: 7.5511e-04 - mae: 0.0212
Epoch 95/100
143/143 [==============================] - 0s 2ms/step - loss: 0.0019 - mae: 0.0307
Epoch 96/100
143/143 [==============================] - 0s 2ms/step - loss: 6.8210e-04 - mae: 0.0173
Epoch 97/100
143/143 [==============================] - 0s 2ms/step - loss: 6.4914e-04 - mae: 0.0182
Epoch 98/100
143/143 [==============================] - 0s 2ms/step - loss: 8.0564e-04 - mae: 0.0206
Epoch 99/100
143/143 [==============================] - 0s 2ms/step - loss: 4.9907e-04 - mae: 0.0180
Epoch 100/100
143/143 [==============================] - 0s 2ms/step - loss: 6.4163e-04 - mae: 0.0196

In [52]:
 loss,mae=model_tanh.evaluate(x_test_mmc,y_test_mmc)

WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_test_function.<locals>.test_function at 0x7f38fd4d4200> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 11ms/step - loss: 0.0066 - mae: 0.0584

In [53]:
loss

0.006568748038262129

In [54]:
mae

0.05838842689990997

In [55]:
y_pred=model_tanh.predict(x_test_mmc)

In [56]:
y_pred

array([[ 0.5495807 ],
       [ 0.45891652],
       [ 0.08528425],
       [ 0.2798815 ],
       [ 0.6044869 ],
       [ 0.02594336],
       [ 0.08662933],
       [ 0.050443  ],
       [ 0.12134465],
       [ 0.07097545],
       [ 0.3511947 ],
       [ 0.03759594],
       [ 0.28197294],
       [ 0.12107328],
       [ 0.799654  ],
       [ 0.04008759],
       [-0.02904518],
       [ 0.12123888],
       [ 0.08110647],
       [ 0.12770447],
       [ 0.09745027],
       [ 0.35489753],
       [ 0.06361948],
       [-0.01377947],
       [ 0.05299545],
       [ 0.62378883],
       [ 0.2161387 ],
       [ 0.24802904],
       [ 0.0409192 ],
       [ 0.2816755 ],
       [ 0.66250956],
       [ 0.01408597],
       [ 0.07132223],
       [ 0.5065148 ],
       [ 0.14730628],
       [ 0.7249445 ],
       [ 0.28328213],
       [ 0.29103047],
       [ 0.04210722],
       [ 0.15990831],
       [ 0.05867149],
       [ 0.21385662],
       [ 0.27042514],
       [ 0.05156122],
       [ 0.03228688],
       [ 0.04976932],
       [ 0.03922933],
       [ 0.04126683],
       [ 0.3382052 ],
       [ 0.20155157],
       [ 0.01118833],
       [ 0.41411546],
       [ 0.04619928],
       [ 0.13197204],
       [ 0.03488723],
       [ 0.3291192 ],
       [ 0.24941371],
       [ 0.21496968],
       [ 0.7018504 ],
       [ 0.01996316],
       [ 0.11501978],
       [ 0.38218057]], dtype=float32)