In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
ionosphere_df=pd.read_csv('/content/sample_data/ionosphere_data_kaggle.csv')

In [5]:
ionosphere_df

     feature1  feature2  feature3  ...  feature33  feature34  label
0           1         0   0.99539  ...    0.18641   -0.45300      g
1           1         0   1.00000  ...   -0.13738   -0.02447      b
2           1         0   1.00000  ...    0.56045   -0.38238      g
3           1         0   1.00000  ...   -0.32382    1.00000      b
4           1         0   1.00000  ...   -0.04608   -0.65697      g
..        ...       ...       ...  ...        ...        ...    ...
346         1         0   0.83508  ...    0.90546   -0.04307      g
347         1         0   0.95113  ...    0.91483    0.04712      g
348         1         0   0.94701  ...    0.92697   -0.00577      g
349         1         0   0.90608  ...    0.87403   -0.16243      g
350         1         0   0.84710  ...    0.85764   -0.06151      g

[351 rows x 35 columns]

In [6]:
ionosphere_df.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [10]:
df1=ionosphere_df[['label']]

In [11]:
df1

    label
0       g
1       b
2       g
3       b
4       g
..    ...
346     g
347     g
348     g
349     g
350     g

[351 rows x 1 columns]

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le=LabelEncoder()

In [14]:
df1_label=le.fit_transform(df1)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [15]:
df1_label

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
df1_df=pd.DataFrame(df1_label,columns=['label'])

In [17]:
df1_df

     label
0        1
1        0
2        1
3        0
4        1
..     ...
346      1
347      1
348      1
349      1
350      1

[351 rows x 1 columns]

In [18]:
df2=ionosphere_df.drop(['label'],axis=1)

In [19]:
df2

     feature1  feature2  feature3  ...  feature32  feature33  feature34
0           1         0   0.99539  ...   -0.54487    0.18641   -0.45300
1           1         0   1.00000  ...   -0.06288   -0.13738   -0.02447
2           1         0   1.00000  ...   -0.24180    0.56045   -0.38238
3           1         0   1.00000  ...    1.00000   -0.32382    1.00000
4           1         0   1.00000  ...   -0.59573   -0.04608   -0.65697
..        ...       ...       ...  ...        ...        ...        ...
346         1         0   0.83508  ...   -0.10714    0.90546   -0.04307
347         1         0   0.95113  ...   -0.00035    0.91483    0.04712
348         1         0   0.94701  ...    0.00442    0.92697   -0.00577
349         1         0   0.90608  ...   -0.03757    0.87403   -0.16243
350         1         0   0.84710  ...   -0.06678    0.85764   -0.06151

[351 rows x 34 columns]

In [22]:
final_df=pd.concat([df2,df1_df],axis=1)

In [23]:
final_df

     feature1  feature2  feature3  ...  feature33  feature34  label
0           1         0   0.99539  ...    0.18641   -0.45300      1
1           1         0   1.00000  ...   -0.13738   -0.02447      0
2           1         0   1.00000  ...    0.56045   -0.38238      1
3           1         0   1.00000  ...   -0.32382    1.00000      0
4           1         0   1.00000  ...   -0.04608   -0.65697      1
..        ...       ...       ...  ...        ...        ...    ...
346         1         0   0.83508  ...    0.90546   -0.04307      1
347         1         0   0.95113  ...    0.91483    0.04712      1
348         1         0   0.94701  ...    0.92697   -0.00577      1
349         1         0   0.90608  ...    0.87403   -0.16243      1
350         1         0   0.84710  ...    0.85764   -0.06151      1

[351 rows x 35 columns]

In [24]:
final_df.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [27]:
x=final_df.drop(['label'],axis=1)

In [28]:
x

     feature1  feature2  feature3  ...  feature32  feature33  feature34
0           1         0   0.99539  ...   -0.54487    0.18641   -0.45300
1           1         0   1.00000  ...   -0.06288   -0.13738   -0.02447
2           1         0   1.00000  ...   -0.24180    0.56045   -0.38238
3           1         0   1.00000  ...    1.00000   -0.32382    1.00000
4           1         0   1.00000  ...   -0.59573   -0.04608   -0.65697
..        ...       ...       ...  ...        ...        ...        ...
346         1         0   0.83508  ...   -0.10714    0.90546   -0.04307
347         1         0   0.95113  ...   -0.00035    0.91483    0.04712
348         1         0   0.94701  ...    0.00442    0.92697   -0.00577
349         1         0   0.90608  ...   -0.03757    0.87403   -0.16243
350         1         0   0.84710  ...   -0.06678    0.85764   -0.06151

[351 rows x 34 columns]

In [29]:
y=final_df[['label']]

In [30]:
y

     label
0        1
1        0
2        1
3        0
4        1
..     ...
346      1
347      1
348      1
349      1
350      1

[351 rows x 1 columns]

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.3, random_state=45)

In [33]:
x_train.shape

(245, 34)

In [34]:
x_test.shape

(106, 34)

In [35]:
y_train.shape

(245, 1)

In [36]:
y_test.shape

(106, 1)

In [37]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
mmc=MinMaxScaler()

In [39]:
x_train_mmc=mmc.fit_transform(x_train)
x_test_mmc=mmc.transform(x_test)

In [40]:
x_train_mmc

array([[1.      , 0.      , 1.      , ..., 0.      , 0.5     , 0.5     ],
       [1.      , 0.      , 0.917135, ..., 0.850055, 0.480085, 0.89722 ],
       [1.      , 0.      , 1.      , ..., 0.444445, 1.      , 0.5     ],
       ...,
       [1.      , 0.      , 0.895785, ..., 0.5643  , 0.5     , 0.5     ],
       [1.      , 0.      , 0.94104 , ..., 0.213115, 0.710945, 0.20957 ],
       [1.      , 0.      , 0.82061 , ..., 0.5     , 0.585365, 0.536585]])

In [41]:
x_test_mmc

array([[1.      , 0.      , 0.93142 , ..., 0.400385, 0.28544 , 0.34023 ],
       [1.      , 0.      , 1.      , ..., 0.32657 , 1.      , 0.674225],
       [1.      , 0.      , 0.87352 , ..., 0.534585, 0.805335, 0.493085],
       ...,
       [1.      , 0.      , 0.93886 , ..., 0.44565 , 0.89538 , 0.497285],
       [1.      , 0.      , 0.84099 , ..., 0.53532 , 0.479935, 0.52293 ],
       [1.      , 0.      , 0.692605, ..., 0.65564 , 0.40467 , 0.64397 ]])

In [42]:
y_train=y_train.to_numpy()

In [43]:
y_train

array([[0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1]])

In [44]:
y_test=y_test.to_numpy()

In [45]:
y_test

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0]])

In [49]:

import tensorflow as tf
from keras import models
from keras import layers
def build_model(act):
 model = models.Sequential()
 model.add(layers.Dense(18, activation=act,input_shape=(34,)))
 model.add(layers.Dense(10, activation=act))
 model.add(layers.Dense(1, activation='sigmoid'))
 model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
 return model

In [50]:
import numpy as np
k = 4
num_val_samples = len(x_train_mmc) // k
num_epochs = 100
all_scores= []
for i in range(k):
 print('processing fold #', i)
 val_data = x_train_mmc[i * num_val_samples: (i + 1) * num_val_samples]
 val_targets = y_train[i * num_val_samples: (i + 1) * num_val_samples]
 partial_train_data = np.concatenate([x_train_mmc[:i * num_val_samples],x_train_mmc[(i + 1) * num_val_samples:]],axis=0)
 partial_train_targets = np.concatenate([y_train[:i * num_val_samples],y_train[(i + 1) * num_val_samples:]],axis=0)
 model = build_model('relu')
 model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
 val_mse, val_accuracy = model.evaluate(val_data, val_targets, verbose=0)
 all_scores.append(val_accuracy)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3

In [51]:
all_scores

[0.9344262480735779,
 0.9672130942344666,
 0.9344262480735779,
 0.8524590134620667]

In [52]:
np.mean(all_scores)

0.9221311509609222

In [53]:
model_relu=build_model('relu')

In [54]:
model_relu.fit(x_train_mmc,y_train,epochs=100,batch_size=1)

Epoch 1/100
245/245 [==============================] - 1s 1ms/step - loss: 0.6095 - accuracy: 0.7269
Epoch 2/100
245/245 [==============================] - 0s 1ms/step - loss: 0.5648 - accuracy: 0.6878
Epoch 3/100
245/245 [==============================] - 0s 1ms/step - loss: 0.5166 - accuracy: 0.7245
Epoch 4/100
245/245 [==============================] - 0s 1ms/step - loss: 0.4858 - accuracy: 0.7760
Epoch 5/100
245/245 [==============================] - 0s 1ms/step - loss: 0.4226 - accuracy: 0.7964
Epoch 6/100
245/245 [==============================] - 0s 1ms/step - loss: 0.4118 - accuracy: 0.8820
Epoch 7/100
245/245 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8788
Epoch 8/100
245/245 [==============================] - 0s 1ms/step - loss: 0.3642 - accuracy: 0.8373
Epoch 9/100
245/245 [==============================] - 0s 1ms/step - loss: 0.3388 - accuracy: 0.8751
Epoch 10/100
245/245 [==============================] - 0s 1ms/step - loss: 0.2930 - accuracy: 0.8829
Epoch 11/100
245/245 [==============================] - 0s 1ms/step - loss: 0.2995 - accuracy: 0.8613
Epoch 12/100
245/245 [==============================] - 0s 1ms/step - loss: 0.2804 - accuracy: 0.8647
Epoch 13/100
245/245 [==============================] - 0s 1ms/step - loss: 0.2868 - accuracy: 0.8899
Epoch 14/100
245/245 [==============================] - 0s 1ms/step - loss: 0.2558 - accuracy: 0.8711
Epoch 15/100
245/245 [==============================] - 0s 1ms/step - loss: 0.2000 - accuracy: 0.9195
Epoch 16/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1703 - accuracy: 0.9267
Epoch 17/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1882 - accuracy: 0.9508
Epoch 18/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1837 - accuracy: 0.9193
Epoch 19/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1544 - accuracy: 0.9228
Epoch 20/100
245/245 [==============================] - 0s 1ms/step - loss: 0.2183 - accuracy: 0.9138
Epoch 21/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1802 - accuracy: 0.9490
Epoch 22/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1294 - accuracy: 0.9608
Epoch 23/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1112 - accuracy: 0.9648
Epoch 24/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1550 - accuracy: 0.9328
Epoch 25/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1413 - accuracy: 0.9547
Epoch 26/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1244 - accuracy: 0.9632
Epoch 27/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1248 - accuracy: 0.9735
Epoch 28/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1195 - accuracy: 0.9815
Epoch 29/100
245/245 [==============================] - 0s 2ms/step - loss: 0.1318 - accuracy: 0.9649
Epoch 30/100
245/245 [==============================] - 0s 1ms/step - loss: 0.2011 - accuracy: 0.9377
Epoch 31/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1204 - accuracy: 0.9473
Epoch 32/100
245/245 [==============================] - 0s 2ms/step - loss: 0.1000 - accuracy: 0.9724
Epoch 33/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0831 - accuracy: 0.9732
Epoch 34/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0747 - accuracy: 0.9842
Epoch 35/100
245/245 [==============================] - 0s 2ms/step - loss: 0.1276 - accuracy: 0.9646
Epoch 36/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1150 - accuracy: 0.9631
Epoch 37/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0959 - accuracy: 0.9685
Epoch 38/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0828 - accuracy: 0.9718
Epoch 39/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0825 - accuracy: 0.9766
Epoch 40/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0544 - accuracy: 0.9770
Epoch 41/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0592 - accuracy: 0.9839
Epoch 42/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1413 - accuracy: 0.9559
Epoch 43/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1264 - accuracy: 0.9683
Epoch 44/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0431 - accuracy: 0.9950
Epoch 45/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0689 - accuracy: 0.9814
Epoch 46/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0747 - accuracy: 0.9787
Epoch 47/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0776 - accuracy: 0.9834
Epoch 48/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0852 - accuracy: 0.9803
Epoch 49/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1123 - accuracy: 0.9662
Epoch 50/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0544 - accuracy: 0.9897
Epoch 51/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0761 - accuracy: 0.9878
Epoch 52/100
245/245 [==============================] - 0s 2ms/step - loss: 0.1173 - accuracy: 0.9544
Epoch 53/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0663 - accuracy: 0.9685
Epoch 54/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0485 - accuracy: 0.9956
Epoch 55/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0812 - accuracy: 0.9739
Epoch 56/100
245/245 [==============================] - 0s 2ms/step - loss: 0.1067 - accuracy: 0.9764
Epoch 57/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1029 - accuracy: 0.9661
Epoch 58/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0737 - accuracy: 0.9856
Epoch 59/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0585 - accuracy: 0.9803
Epoch 60/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0593 - accuracy: 0.9812
Epoch 61/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0602 - accuracy: 0.9875
Epoch 62/100
245/245 [==============================] - 0s 1ms/step - loss: 0.1052 - accuracy: 0.9606
Epoch 63/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0349 - accuracy: 0.9952
Epoch 64/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0489 - accuracy: 0.9820
Epoch 65/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0730 - accuracy: 0.9731
Epoch 66/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0596 - accuracy: 0.9825
Epoch 67/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0369 - accuracy: 0.9898
Epoch 68/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0784 - accuracy: 0.9786
Epoch 69/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0500 - accuracy: 0.9896
Epoch 70/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0498 - accuracy: 0.9918
Epoch 71/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0542 - accuracy: 0.9877
Epoch 72/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0510 - accuracy: 0.9903
Epoch 73/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0829 - accuracy: 0.9838
Epoch 74/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0336 - accuracy: 0.9914
Epoch 75/100
245/245 [==============================] - 0s 2ms/step - loss: 0.1046 - accuracy: 0.9723
Epoch 76/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0413 - accuracy: 0.9892
Epoch 77/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0312 - accuracy: 0.9896
Epoch 78/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0700 - accuracy: 0.9694
Epoch 79/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0763 - accuracy: 0.9886
Epoch 80/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0479 - accuracy: 0.9782
Epoch 81/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0849 - accuracy: 0.9806
Epoch 82/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0599 - accuracy: 0.9818
Epoch 83/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0542 - accuracy: 0.9869
Epoch 84/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0544 - accuracy: 0.9876
Epoch 85/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0306 - accuracy: 0.9921
Epoch 86/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0616 - accuracy: 0.9776
Epoch 87/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0615 - accuracy: 0.9839
Epoch 88/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0515 - accuracy: 0.9847
Epoch 89/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0757 - accuracy: 0.9742
Epoch 90/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0354 - accuracy: 0.9948
Epoch 91/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0673 - accuracy: 0.9739
Epoch 92/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0512 - accuracy: 0.9839
Epoch 93/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0533 - accuracy: 0.9849
Epoch 94/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0376 - accuracy: 0.9921
Epoch 95/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0418 - accuracy: 0.9942
Epoch 96/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0538 - accuracy: 0.9897
Epoch 97/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0888 - accuracy: 0.9668
Epoch 98/100
245/245 [==============================] - 0s 2ms/step - loss: 0.1097 - accuracy: 0.9871
Epoch 99/100
245/245 [==============================] - 0s 2ms/step - loss: 0.0635 - accuracy: 0.9858
Epoch 100/100
245/245 [==============================] - 0s 1ms/step - loss: 0.0569 - accuracy: 0.9882

In [55]:
loss,accuracy=model_relu.evaluate(x_test_mmc,y_test)

WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_test_function.<locals>.test_function at 0x7f574029f8c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
4/4 [==============================] - 0s 5ms/step - loss: 0.3998 - accuracy: 0.9245

In [56]:
loss

0.3997753858566284

In [57]:
accuracy

0.9245283007621765

In [59]:
y_pred=model_relu.predict(x_test_mmc)

In [60]:
y_pred

array([[9.99991894e-01],
       [1.00000000e+00],
       [9.96724308e-01],
       [9.99958038e-01],
       [9.99558687e-01],
       [9.99892712e-01],
       [9.99991000e-01],
       [2.17795372e-04],
       [9.99860764e-01],
       [5.33238875e-08],
       [1.71845257e-02],
       [9.94336963e-01],
       [9.99998689e-01],
       [9.99998510e-01],
       [9.99973059e-01],
       [1.06390369e-04],
       [8.89342308e-01],
       [9.99982595e-01],
       [4.37297331e-07],
       [9.99999583e-01],
       [9.99992073e-01],
       [9.99738455e-01],
       [9.99986649e-01],
       [9.99956250e-01],
       [9.85340476e-01],
       [8.86275245e-07],
       [7.49267102e-08],
       [1.58668649e-06],
       [9.99822736e-01],
       [4.01395445e-10],
       [9.98533428e-01],
       [2.72098184e-03],
       [9.99978304e-01],
       [9.99806166e-01],
       [3.28747690e-01],
       [9.95524168e-01],
       [9.99857247e-01],
       [2.18949020e-02],
       [9.99957919e-01],
       [9.99876618e-01],
       [1.21314042e-04],
       [9.99782801e-01],
       [3.48123908e-03],
       [9.99903560e-01],
       [9.46223736e-04],
       [3.10984254e-03],
       [2.59373664e-05],
       [6.20812178e-04],
       [9.99309897e-01],
       [9.95796323e-01],
       [9.99968529e-01],
       [1.06412845e-05],
       [6.69028499e-10],
       [9.99999762e-01],
       [9.99950767e-01],
       [1.24796244e-07],
       [5.11366129e-03],
       [2.54482031e-04],
       [9.95553136e-01],
       [9.99832153e-01],
       [9.99965191e-01],
       [9.89212632e-01],
       [1.14212334e-02],
       [9.79267895e-01],
       [9.99868453e-01],
       [9.51760709e-01],
       [9.99959946e-01],
       [9.99994218e-01],
       [3.74454778e-08],
       [2.58803516e-06],
       [9.99280393e-01],
       [9.99070168e-01],
       [2.65603290e-07],
       [2.82306883e-06],
       [9.99968767e-01],
       [9.99884486e-01],
       [9.76628900e-01],
       [9.99986529e-01],
       [9.99119878e-01],
       [8.80625844e-03],
       [9.99999642e-01],
       [9.99968648e-01],
       [9.99999166e-01],
       [9.99023080e-01],
       [9.98980880e-01],
       [1.00000000e+00],
       [9.65718448e-01],
       [9.22145784e-01],
       [9.99997139e-01],
       [9.99998331e-01],
       [1.13178750e-04],
       [4.67920572e-01],
       [9.89352942e-01],
       [9.99765396e-01],
       [6.18233681e-01],
       [9.99999762e-01],
       [9.99768138e-01],
       [9.13196385e-01],
       [9.99937534e-01],
       [9.99994636e-01],
       [9.98944044e-04],
       [3.99259443e-06],
       [9.99948084e-01],
       [9.99765158e-01],
       [9.99894738e-01],
       [8.30918610e-01]], dtype=float32)